# These constants have been generated by an LLM

UNITS = {
    "teaspoon", "teaspoons", "tsp", "tsps",
    "tablespoon", "tablespoons", "tbsp", "tbsps",
    "cup", "cups",
    "ounce", "ounces", "oz",
    "pound", "pounds", "lb", "lbs",
    "gram", "grams", "g", "kg",
    "milliliter", "milliliters", "ml",
    "liter", "liters",
    "clove", "cloves",
    "slice", "slices",
    "can", "cans",
    "package", "packages",
    "pinch", "dash", "bunch",
    "fluid", "fl",                  
    "spear", "spears",
    "fillet", "fillets",
    "piece", "pieces",
    "strip", "strips",
    "cube", "cubes",
    "chunk", "chunks",
    "wedge", "wedges",
    "stalk", "stalks",
    "head", "heads",
    "link", "links",
    "stick", "sticks",
    "sheet", "sheets",
    "scoop", "scoops",
    "drop", "drops",
}

PREP_DESCRIPTORS = {
    "chopped", "minced", "diced", "sliced", "halved", "seeded",
    "trimmed", "peeled", "crushed", "grated", "shredded", "sifted",
    "softened", "melted", "beaten", "crumbled",
    "divided", "optional",
    "drained", "rinsed",
    "thawed", "cooked",
    "packed",                      
    "freshly",                    
    "finely", "roughly", "thinly", 
    "well",                        
    "boneless", "skinless",        
}

NOISE_PHRASES = [
    "to taste",
    "as needed",
    "or as needed",
    "or more as needed",
    "for decoration",
    "for garnish",
    "for serving",
    "to serve",
    "if desired",
    "well drained",
    "drained and rinsed",
    "rinsed and drained",
    "cut into matchsticks",
    "cut into strips",
    "cut into cubes",
    "cut into chunks",
    "cut into pieces",
    "cut into wedges",
    "cut into bite size pieces",
    "cut into bite sized pieces",
    "cut into bite-sized pieces",
    "for frying",
    "bone in",
    "with spice packet",
    "in syrup",
    "in juice",
    "in water",
]

SYNONYMS = {
    "confectioner s sugar": "confectioners sugar",
    "powdered sugar":       "confectioners sugar",
    "icing sugar":          "confectioners sugar",

    "garbanzo bean":  "chickpeas",
    "garbanzo beans": "chickpeas",
    "chickpea":       "chickpeas",

    "steel cut oats":    "oats",
    "rolled oats":       "oats",
    "old fashioned oats":"oats",

    "spring onion":  "green onion",
    "spring onions": "green onion",
    "scallion":      "green onion",
    "scallions":     "green onion",

    "salmon fillet":  "salmon",
    "salmon fillets": "salmon",

    "asparagus spear":  "asparagus",
    "asparagus spears": "asparagus",

    "dry lentils": "lentils",

    "cherry pie filling":         "cherries",
    "frozen whipped topping":     "whipped topping",
    "refrigerated biscuit dough": "biscuits",
    "refrigerated biscuits":      "biscuits",
    "refrigerated crescent roll dough": "crescent rolls",
    "refrigerated pie crusts":    "pie crust",

    "unsulfured molasses": "molasses",

    "corned beef brisket": "corned beef",

    "fully cooked bone in ham": "ham",

    "grenadine syrup": "grenadine",

    "pork spareribs": "pork ribs",
}

TO_DISCARD = {
    "", "or", "and", "needed", "taste",
    "matchstick", "matchsticks",
    "chuck", "syrup", "mix",
}
